@echo off
@rem ==============================================================================
@rem Remove every Android build artifact of the engine module tree and the Samples.
@rem
@rem   clean-android.bat [-y]
@rem     -y   delete without asking
@rem
@rem Removed, per Android project root:
@rem   .gradle                gradle project cache
@rem   build                  root project output
@rem   .externalNativeBuild   native tree of pre 4.0 AGP
@rem and per module (a subdirectory holding a build.gradle):
@rem   build                  gradle / AGP output, APKs
@rem   libs                   .so staged for packaging
@rem   .externalNativeBuild
@rem   .cxx                   delegated to clean-android-cxx.bat
@rem
@rem Deliberately kept, even though .gitignore lists some of them - none is build
@rem output:
@rem   local.properties   machine SDK / NDK paths, annoying to re-enter
@rem   .idea, *.iml       IDE configuration, partly under version control
@rem   captures           profiler captures you took on purpose
@rem
@rem SAFETY: a few directories that .gitignore lists are in fact tracked, so they
@rem hold committed files despite being "ignored":
@rem   Samples/InputApp/Android/.gradle      gradle cache, committed by accident
@rem   Samples/PlatformApp/Android/app/libs  prebuilt .so for armeabi / x86
@rem Deleting those would destroy repository content, so every candidate is checked
@rem against `git ls-files` first and anything git knows about is skipped and
@rem reported. That is also why git is required rather than optional.
@rem
@rem Everything actually removed is regenerated by the next gradle build. Expect
@rem tens of GB.
@rem
@rem Keep this file ASCII only: cmd.exe decodes .bat files with the OEM code page.
@rem ==============================================================================

setlocal EnableDelayedExpansion

for %%i in ("%~dp0..") do set "SOURCE_DIR=%%~fi"
for %%i in ("%~dp0..\..") do set "REPO_ROOT=%%~fi"
set "CXX_SCRIPT=%~dp0clean-android-cxx.bat"
set "TRACKED=%TEMP%\t3d-clean-android-tracked.txt"

if not exist "%SOURCE_DIR%\Samples" (
    echo ERROR: Samples directory not found at "%SOURCE_DIR%\Samples".
    exit /b 1
)
if not exist "%CXX_SCRIPT%" (
    echo ERROR: clean-android-cxx.bat not found at "%CXX_SCRIPT%".
    exit /b 1
)

where git >nul 2>&1
if errorlevel 1 (
    echo ERROR: git was not found on PATH.
    echo        This script will not delete anything without it - see the SAFETY
    echo        note at the top of this file.
    exit /b 1
)
pushd "%REPO_ROOT%"
git ls-files > "%TRACKED%" 2>nul
set "GIT_RC=!ERRORLEVEL!"
popd
if not "!GIT_RC!" == "0" (
    echo ERROR: `git ls-files` failed in "%REPO_ROOT%".
    exit /b 1
)

set "ASSUME_YES="
if /i "%~1" == "-y" set "ASSUME_YES=1"
if /i "%~1" == "/y" set "ASSUME_YES=1"

@rem ------------------------------------------------------------------------------
@rem Scan. .cxx is only counted here - clean-android-cxx.bat lists it in detail
@rem when it runs, no point printing the same tree twice.
@rem ------------------------------------------------------------------------------
set /a DELETABLE=0
set /a SKIPPED=0
set /a CXX_FOUND=0
echo Scanning "%SOURCE_DIR%" ...
echo.
call :for_each_root :scan

echo.
echo   plus %CXX_FOUND% module/.cxx tree^(s^) via clean-android-cxx.bat
if %SKIPPED% gtr 0 (
    echo.
    echo   [tracked] = git tracks files there, so it is kept. %SKIPPED% of them.
)
echo.
if %DELETABLE% == 0 if %CXX_FOUND% == 0 (
    echo Nothing to do.
    del "%TRACKED%" >nul 2>&1
    exit /b 0
)
echo %DELETABLE% directory^(ies^) to delete, plus the .cxx trees.

if not defined ASSUME_YES (
    echo.
    set /p "ANSWER=Delete them? [y/N] "
    if /i not "!ANSWER!" == "y" (
        echo Aborted, nothing was deleted.
        del "%TRACKED%" >nul 2>&1
        exit /b 1
    )
)
echo.

set /a FAILED=0

@rem .cxx first: it is the one that blocks a clean re-configure, so if the run is
@rem interrupted half way that part is already done.
if %CXX_FOUND% gtr 0 (
    call "%CXX_SCRIPT%" -y
    if errorlevel 1 set /a FAILED+=1
    echo.
)

call :for_each_root :clean
del "%TRACKED%" >nul 2>&1

echo.
if %FAILED% == 0 (
    echo Done.
    exit /b 0
)
echo %FAILED% item^(s^) could not be removed.
exit /b 1

@rem ------------------------------------------------------------------------------
@rem Call %1 once per Android project root, as: <label> "<abs path>" "<label path>".
@rem A root is a directory holding the top level build.gradle; its modules are the
@rem subdirectories that hold one too.
@rem ------------------------------------------------------------------------------
:for_each_root
if exist "%SOURCE_DIR%\Platform\Android\build.gradle" (
    call %~1 "%SOURCE_DIR%\Platform\Android" "Platform\Android"
)
for /d %%d in ("%SOURCE_DIR%\Samples\*") do (
    if exist "%%~fd\Android\build.gradle" call %~1 "%%~fd\Android" "%%~nxd\Android"
)
exit /b 0

@rem ------------------------------------------------------------------------------
:scan
set "ITEMS="
for %%k in (.gradle build .externalNativeBuild) do call :scan_kind "%~1\%%k" "%%k"
for /d %%m in ("%~1\*") do (
    if exist "%%~fm\build.gradle" (
        if exist "%%~fm\.cxx\" set /a CXX_FOUND+=1
        for %%k in (build libs .externalNativeBuild) do call :scan_kind "%%~fm\%%k" "%%~nxm\%%k"
    )
)
if defined ITEMS echo   %~2:!ITEMS!
exit /b 0

:scan_kind
if not exist "%~1\" exit /b 0
call :is_tracked "%~1"
if errorlevel 1 (
    set /a SKIPPED+=1
    set "ITEMS=!ITEMS! %~2[tracked]"
) else (
    set /a DELETABLE+=1
    set "ITEMS=!ITEMS! %~2"
)
exit /b 0

@rem ------------------------------------------------------------------------------
:clean
for %%k in (.gradle build .externalNativeBuild) do call :try_remove "%~1\%%k" "%~2\%%k"
for /d %%m in ("%~1\*") do (
    if exist "%%~fm\build.gradle" (
        for %%k in (build libs .externalNativeBuild) do call :try_remove "%%~fm\%%k" "%~2\%%~nxm\%%k"
    )
)
exit /b 0

:try_remove
if not exist "%~1\" exit /b 0
call :is_tracked "%~1"
if errorlevel 1 exit /b 0
echo Removing %~2
rd /s /q "%~1"
@rem Android Studio and the gradle daemon keep handles on these trees, so rd can
@rem delete part of one and still report success. Re-check instead of claiming a
@rem clean tree - that state is far harder to diagnose later.
if exist "%~1\" (
    set /a FAILED+=1
    echo   [ERROR] delete failed. Close Android Studio, stop the gradle daemon, retry.
)
exit /b 0

@rem ------------------------------------------------------------------------------
@rem errorlevel 1 when git tracks anything under %1. Prefix match on the repo
@rem relative path; `git ls-files` prints forward slashes.
@rem ------------------------------------------------------------------------------
:is_tracked
set "REL=%~1"
set "REL=!REL:%REPO_ROOT%\=!"
set "REL=!REL:\=/!"
findstr /b /i /c:"!REL!/" "%TRACKED%" >nul 2>&1
if errorlevel 1 exit /b 0
exit /b 1
