#Requires -Version 3.0
<#
.SYNOPSIS
    Turn the environment delta of a vcvarsall.bat run into a replayable .cmd.

.DESCRIPTION
    setup-msvc-env.bat dumps 'set' before and after calling vcvarsall.bat and
    hands both files here. Everything vcvarsall added or changed is written out
    as 'set "NAME=VALUE"' lines so that the next run can replay the environment
    in a few milliseconds instead of paying for vcvarsall again.

    Keep the generated file ASCII / OEM: cmd.exe decodes .cmd files with the OEM
    code page, which is also why both dumps are read as OEM here.
#>
param(
    [Parameter(Mandatory = $true)][string]$Before,
    [Parameter(Mandatory = $true)][string]$After,
    [Parameter(Mandatory = $true)][string]$Output,
    [Parameter(Mandatory = $true)][string]$Stamp
)

$ErrorActionPreference = 'Stop'

# Volatile or session specific variables. Replaying them would either be
# meaningless or actively wrong in the shell that calls the cache.
$SkipNames = @(
    'PROMPT', 'CD', 'CMDCMDLINE', 'CMDEXTVERSION', 'ERRORLEVEL',
    'RANDOM', 'TIME', 'DATE', 'CMDLINE', '_'
)

function Read-EnvDump([string]$Path)
{
    $map = New-Object System.Collections.Specialized.OrderedDictionary(
        [System.StringComparer]::OrdinalIgnoreCase)

    foreach ($line in (Get-Content -LiteralPath $Path -Encoding Oem))
    {
        # A variable name cannot be empty, so '=' at index 0 means this is a
        # continuation of a multi line value rather than a new entry.
        $sep = $line.IndexOf('=')
        if ($sep -lt 1)
        {
            continue
        }
        $map[$line.Substring(0, $sep)] = $line.Substring($sep + 1)
    }

    # Wrap in an array: PowerShell enumerates an IEnumerable return value, and an
    # OrderedDictionary would come back as a list of DictionaryEntry instead.
    return , $map
}

# '%' starts a variable expansion when the cache is replayed, so it has to be
# doubled to survive the round trip.
function ConvertTo-CmdLiteral([string]$Value)
{
    return $Value.Replace('%', '%%')
}

# Not $before / $after: variable names are case insensitive here, so those would
# write back into the [string] typed parameters and get coerced to a string.
$beforeEnv = Read-EnvDump $Before
$afterEnv = Read-EnvDump $After

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('@rem Generated by setup-msvc-env.bat -- do not edit.')
$lines.Add('@rem Delete this file, or pass -refresh, to rebuild it from vcvarsall.bat.')
$lines.Add('@set "T3D_MSVC_ENV_CACHE_STAMP=' + (ConvertTo-CmdLiteral $Stamp) + '"')

foreach ($name in $afterEnv.Keys)
{
    if ($SkipNames -contains $name)
    {
        continue
    }
    # vcvarsall keeps a copy of the pre-init state under these names purely so
    # it can detect a second run; replaying them would fake an initialized env.
    if ($name -like '__VSCMD_PREINIT*')
    {
        continue
    }

    $newValue = $afterEnv[$name]
    $hadBefore = $beforeEnv.Contains($name)
    $oldValue = if ($hadBefore) { $beforeEnv[$name] } else { $null }

    if ($hadBefore -and $oldValue -ceq $newValue)
    {
        continue
    }

    # Record only the part vcvarsall prepended to PATH. Baking in the whole PATH
    # would pin it to whatever was installed the day the cache was recorded.
    if ($name -ieq 'PATH' -and $hadBefore -and
        $newValue.EndsWith($oldValue, [System.StringComparison]::OrdinalIgnoreCase))
    {
        $prefix = $newValue.Substring(0, $newValue.Length - $oldValue.Length)
        $lines.Add('@set "PATH=' + (ConvertTo-CmdLiteral $prefix) + '%PATH%"')
        continue
    }

    # 'set "NAME=VALUE"' cannot carry a value that contains a double quote, and
    # dropping the quoting would break on '&' and friends instead.
    if ($newValue.Contains('"'))
    {
        $lines.Add('@rem skipped ' + $name + ': the value contains a double quote')
        continue
    }

    $lines.Add('@set "' + $name + '=' + (ConvertTo-CmdLiteral $newValue) + '"')
}

$lines.Add('@exit /b 0')

Set-Content -LiteralPath $Output -Value $lines -Encoding Oem
exit 0
