// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetPackage.proto

#include "NetPackage.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace Tiny3D {
namespace Editor {
class NetPackageHeaderDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<NetPackageHeader> _instance;
} _NetPackageHeader_default_instance_;
}  // namespace Editor
}  // namespace Tiny3D
static void InitDefaultsscc_info_NetPackageHeader_NetPackage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Tiny3D::Editor::_NetPackageHeader_default_instance_;
    new (ptr) ::Tiny3D::Editor::NetPackageHeader();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Tiny3D::Editor::NetPackageHeader::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NetPackageHeader_NetPackage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_NetPackageHeader_NetPackage_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_NetPackage_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_NetPackage_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_NetPackage_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_NetPackage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Tiny3D::Editor::NetPackageHeader, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Tiny3D::Editor::NetPackageHeader, magic_),
  PROTOBUF_FIELD_OFFSET(::Tiny3D::Editor::NetPackageHeader, version_),
  PROTOBUF_FIELD_OFFSET(::Tiny3D::Editor::NetPackageHeader, length_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Tiny3D::Editor::NetPackageHeader)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Tiny3D::Editor::_NetPackageHeader_default_instance_),
};

const char descriptor_table_protodef_NetPackage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020NetPackage.proto\022\rTiny3D.Editor\"B\n\020Net"
  "PackageHeader\022\r\n\005magic\030\001 \001(\007\022\017\n\007version\030"
  "\002 \001(\007\022\016\n\006length\030\003 \001(\005b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_NetPackage_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_NetPackage_2eproto_sccs[1] = {
  &scc_info_NetPackageHeader_NetPackage_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_NetPackage_2eproto_once;
static bool descriptor_table_NetPackage_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_NetPackage_2eproto = {
  &descriptor_table_NetPackage_2eproto_initialized, descriptor_table_protodef_NetPackage_2eproto, "NetPackage.proto", 109,
  &descriptor_table_NetPackage_2eproto_once, descriptor_table_NetPackage_2eproto_sccs, descriptor_table_NetPackage_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_NetPackage_2eproto::offsets,
  file_level_metadata_NetPackage_2eproto, 1, file_level_enum_descriptors_NetPackage_2eproto, file_level_service_descriptors_NetPackage_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_NetPackage_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_NetPackage_2eproto), true);
namespace Tiny3D {
namespace Editor {

// ===================================================================

void NetPackageHeader::InitAsDefaultInstance() {
}
class NetPackageHeader::_Internal {
 public:
};

NetPackageHeader::NetPackageHeader()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Tiny3D.Editor.NetPackageHeader)
}
NetPackageHeader::NetPackageHeader(const NetPackageHeader& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&magic_, &from.magic_,
    static_cast<size_t>(reinterpret_cast<char*>(&length_) -
    reinterpret_cast<char*>(&magic_)) + sizeof(length_));
  // @@protoc_insertion_point(copy_constructor:Tiny3D.Editor.NetPackageHeader)
}

void NetPackageHeader::SharedCtor() {
  ::memset(&magic_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&length_) -
      reinterpret_cast<char*>(&magic_)) + sizeof(length_));
}

NetPackageHeader::~NetPackageHeader() {
  // @@protoc_insertion_point(destructor:Tiny3D.Editor.NetPackageHeader)
  SharedDtor();
}

void NetPackageHeader::SharedDtor() {
}

void NetPackageHeader::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const NetPackageHeader& NetPackageHeader::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_NetPackageHeader_NetPackage_2eproto.base);
  return *internal_default_instance();
}


void NetPackageHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:Tiny3D.Editor.NetPackageHeader)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&magic_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&length_) -
      reinterpret_cast<char*>(&magic_)) + sizeof(length_));
  _internal_metadata_.Clear();
}

const char* NetPackageHeader::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // fixed32 magic = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          magic_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<::PROTOBUF_NAMESPACE_ID::uint32>(ptr);
          ptr += sizeof(::PROTOBUF_NAMESPACE_ID::uint32);
        } else goto handle_unusual;
        continue;
      // fixed32 version = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          version_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<::PROTOBUF_NAMESPACE_ID::uint32>(ptr);
          ptr += sizeof(::PROTOBUF_NAMESPACE_ID::uint32);
        } else goto handle_unusual;
        continue;
      // int32 length = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          length_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* NetPackageHeader::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Tiny3D.Editor.NetPackageHeader)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // fixed32 magic = 1;
  if (this->magic() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFixed32ToArray(1, this->_internal_magic(), target);
  }

  // fixed32 version = 2;
  if (this->version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFixed32ToArray(2, this->_internal_version(), target);
  }

  // int32 length = 3;
  if (this->length() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_length(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Tiny3D.Editor.NetPackageHeader)
  return target;
}

size_t NetPackageHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Tiny3D.Editor.NetPackageHeader)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // fixed32 magic = 1;
  if (this->magic() != 0) {
    total_size += 1 + 4;
  }

  // fixed32 version = 2;
  if (this->version() != 0) {
    total_size += 1 + 4;
  }

  // int32 length = 3;
  if (this->length() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_length());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NetPackageHeader::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Tiny3D.Editor.NetPackageHeader)
  GOOGLE_DCHECK_NE(&from, this);
  const NetPackageHeader* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<NetPackageHeader>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Tiny3D.Editor.NetPackageHeader)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Tiny3D.Editor.NetPackageHeader)
    MergeFrom(*source);
  }
}

void NetPackageHeader::MergeFrom(const NetPackageHeader& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Tiny3D.Editor.NetPackageHeader)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.magic() != 0) {
    _internal_set_magic(from._internal_magic());
  }
  if (from.version() != 0) {
    _internal_set_version(from._internal_version());
  }
  if (from.length() != 0) {
    _internal_set_length(from._internal_length());
  }
}

void NetPackageHeader::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Tiny3D.Editor.NetPackageHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NetPackageHeader::CopyFrom(const NetPackageHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Tiny3D.Editor.NetPackageHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NetPackageHeader::IsInitialized() const {
  return true;
}

void NetPackageHeader::InternalSwap(NetPackageHeader* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(magic_, other->magic_);
  swap(version_, other->version_);
  swap(length_, other->length_);
}

::PROTOBUF_NAMESPACE_ID::Metadata NetPackageHeader::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Editor
}  // namespace Tiny3D
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Tiny3D::Editor::NetPackageHeader* Arena::CreateMaybeMessage< ::Tiny3D::Editor::NetPackageHeader >(Arena* arena) {
  return Arena::CreateInternal< ::Tiny3D::Editor::NetPackageHeader >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
